spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

files:
  images:
    dir: /var/blog/images
